name: "Weewx-magi"
description: "Weewx home-assistant"
version: "1.0"
slug: "weewx-magi"

map:
  - type: addon_config
    read_only: False
  - type: share
    read_only: False
  

init: false

ports:
  8000/tcp: 8000
  8020/tcp: 8020

arch:
  - armv7
  - aarch64
