name: "Weewx"
description: "Addon to run weewx inside HA"
version: "1.1.4"
slug: "weewx"

map:
  - type: addon_config
    read_only: False
  - type: share
    read_only: False
  

init: false

ports:
  8000/tcp: 8000
  8020/tcp: 8020

arch:
  - armv7
